#!/usr/bin/env python3

# https://ukbaz.github.io/howto/beacon_scan_cmd_line.html


import sys
import argparse
import re

def checkMacAddress( mac ):
    try:
        if re.match("[0-9a-f]{2}([-:])[0-9a-f]{2}(\\1[0-9a-f]{2}){4}$", mac.lower()):
            return mac.lower()
    except:
        pass
    raise argparse.ArgumentTypeError("%s is not a MAC address" % mac)

def initializeArgParser():
	parser = argparse.ArgumentParser( description = "Beacons tools" )
	# MAC addresses list
	parser.add_argument( '-m', '--mac', 
						action = 'append',
						dest = "mac",
						type=checkMacAddress,
						help = "Look for this MAC address." )

	try:
		opts = parser.parse_args()
	except Exception as e:
		parser.error( "Error: " + str( e ) )
		opts = None

	return opts

# ----- main -----
if __name__ == "__main__":
	opts = initializeArgParser()
	if None == opts:
		sys.exit()

